### ISSUE TITLE
Armor Inventory doesn't equip

### ISSUE THREAD

**Issue by nasiridrishi** [poggit-orphanage/AdvancedKits#9]
version: 5.1.0-11
PocketMine-MP 1.7dev-717 with API 3.0.0-ALPHA11
Issue:
 Armor inventory such as helmet, Lagging's, Chestplate, boots do not equip and there is no errors on console as well!
```
pvp:
  # Fromat: "id:damage:count:name:ench_name:ench_level"

  # If you want ONLY custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want ONLY enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "267:0:1:pvp:sharpness:1"
  - "261:0:1"
  - "364:0:60"
  - "322:0:2"
  - "262:0:64"
  helmet: "306:0:1:pvp:Overload:2"
  chestplate: "307:0:1:pvp:Overload:2"
  leggings: "308:0:1:pvp:Overload:2"
  boots: "309:0:1:pvp:Overload:2"

  commands: []

  cooldown:
    hours: 0
    minutes: 0

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects: []
  
  money: 0

  # If you do not use pureperms, use 'worlds' to specify in which worlds you want this kit to be used
  worlds:
  - "kitpvp"
  # If you do not use pureperms, use 'users' to specify which players will be able to get this kit
  users:
  - "luca28pet"
  - "dioconsole"
```
